set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

find_program(CLANG clang REQUIRED)
find_program(CLANGXX clang++ REQUIRED)
find_program(LLD ld.lld REQUIRED)
find_program(NASM nasm REQUIRED)

set(CMAKE_C_COMPILER ${CLANG})
set(CMAKE_CXX_COMPILER ${CLANGXX})
set(CMAKE_ASM_NASM_COMPILER ${NASM})

set(CMAKE_C_COMPILER_TARGET x86_64-elf)
set(CMAKE_CXX_COMPILER_TARGET x86_64-elf)

set(CMAKE_C_FLAGS_INIT "--target=x86_64-elf")
set(CMAKE_CXX_FLAGS_INIT "--target=x86_64-elf")

execute_process(
    COMMAND nix eval --raw --impure --expr "with import <nixpkgs> {}; libcxx.dev"
    OUTPUT_VARIABLE NIX_LIBCXX_DEV
    OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE NIX_LIBCXX_DEV_RESULT
)

if(NIX_LIBCXX_DEV_RESULT EQUAL 0)
    set(CMAKE_CXX_FLAGS_INIT "${CMAKE_CXX_FLAGS_INIT} -isystem ${NIX_LIBCXX_DEV}/include/c++/v1")
endif()

set(CMAKE_LINKER ${LLD})

find_program(LLD ld.lld REQUIRED)

set(CMAKE_LINKER ${LLD})

set(CMAKE_C_LINK_EXECUTABLE
    "${LLD} <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>"
)

set(CMAKE_CXX_LINK_EXECUTABLE
    "${LLD} <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>"
)
